# Generated by Django 2.2.6 on 2019-10-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('P', 'Normal'), ('L', 'Luxury'), ('S', 'Super-Luxury')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arr_time', models.TimeField()),
                ('dep_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.ManyToManyField(to='trains.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Carriage')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stations', models.ManyToManyField(through='trains.Include', to='trains.Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Train')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.TypeSchedule')),
            ],
        ),
        migrations.AddField(
            model_name='include',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Schedule'),
        ),
        migrations.AddField(
            model_name='include',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Station'),
        ),
        migrations.AddField(
            model_name='carriage',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Train'),
        ),
    ]
