# Generated by Django 2.2.6 on 2019-10-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emoloyee',
            new_name='Employee',
        ),
    ]
